name: Ubuntu 22.04 Humble Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: self-hosted
    container:
      image: osrf/ros:humble-desktop-full-jammy
      
    steps:
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.2.7
      with:
        target-ros2-distro: humble
        import-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
